export const WEATHER_API_KEY: string = "appid=3f6f5b5d8c57fa8889630a6fc3cd6c72&"
export const WEATHER_API_URL: string = "https://api.openweathermap.org/"
export const WEATHER_API_BASE_URL: string = "data/2.5/weather?"
export const GEOLOCATION_DIRECT_API_BASE_URL: string = "geo/1.0/direct?"
export const GEOLOCATION_REVERSE_API_BASE_URL: string = "geo/1.0/reverse?"